language: node_js
sudo: true
node_js:
  - '9.3.0'
cache:
  directories:
    - node_modules
before_install:
    - npm install
script:
  - npm run test
  - npm run coverage
after_script:
  - npm run report